# Generated by Django 4.0 on 2024-02-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0005_projcets_name_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projcets',
            name='user',
        ),
        migrations.DeleteModel(
            name='R_person',
        ),
        migrations.DeleteModel(
            name='Projcets',
        ),
    ]
